; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
lib_compat_mode = strict

[env:wemostag01]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF53
board = wemos_d1_uno32
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++23 -fmodules-ts --define-macro=TAGCODE -DTAG_ID=1 -DBOARD=2
upload_port = /dev/ttyUSB1
lib_deps = ayushsharma82/ElegantOTA@^3.1.7

[env:wemosanchor01]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF53
board = wemos_d1_uno32
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++23 -fmodules-ts --define-macro=ANCHORCODE -DANCHOR_ID=1 -DBOARD=2
upload_port = /dev/ttyUSB0
lib_deps = ayushsharma82/ElegantOTA@^3.1.7

[env:wroomanchor02]
platform = https://github.com/Jason2866/platform-espressif32.git#Arduino/IDF53
board = upesy_wroom
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++23 -fmodules-ts --define-macro=ANCHORCODE -DANCHOR_ID=2 -DBOARD=1
upload_port = /dev/ttyUSB2
lib_deps = ayushsharma82/ElegantOTA@^3.1.7
