; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
lib_deps = https://github.com/espressif/arduino-esp32.git
upload_speed = 921600

; [env:wemostag01]
; board = wemos_d1_uno32
; build_flags = -std=gnu++23 -fmodules-ts --define-macro=TAGCODE -DTAG_ID=1 -DBOARD=2
; upload_port = /dev/ttyUSB0

; [env:wemostag02]
; board = wemos_d1_uno32
; build_flags = -std=gnu++23 -fmodules-ts --define-macro=TAGCODE -DTAG_ID=2 -DBOARD=2
; upload_port = /dev/ttyUSB1

; [env:wroomtag01]
; board = upesy_wroom
; build_flags = -std=gnu++23 -fmodules-ts --define-macro=TAGCODE -DTAG_ID=1 -DBOARD=1
; upload_port = /dev/ttyUSB2



[env:wroomanchor01]
board = upesy_wroom
build_flags = --define-macro=ANCHORCODE -DANCHOR_ID=1 -DBOARD=1
upload_port = /dev/ttyUSB0
lib_deps = knolleary/PubSubClient@^2.8

[env:wroomanchor02]
board = upesy_wroom
build_flags = --define-macro=ANCHORCODE -DANCHOR_ID=2 -DBOARD=1
upload_port = /dev/ttyUSB1
lib_deps = knolleary/PubSubClient@^2.8

[env:wroomanchor03]
board = upesy_wroom
build_flags = --define-macro=ANCHORCODE -DANCHOR_ID=3 -DBOARD=1
upload_port = /dev/ttyUSB2
lib_deps = knolleary/PubSubClient@^2.8

[env:wemosanchor01]
board = wemos_d1_uno32
build_flags = --define-macro=ANCHORCODE -DANCHOR_ID=2 -DBOARD=2
upload_port = /dev/ttyUSB0
lib_deps = knolleary/PubSubClient@^2.8

; [env:wemosanchor02]
; board = wemos_d1_uno32
; build_flags = --define-macro=ANCHORCODE -DANCHOR_ID=1 -DBOARD=2
; upload_port = /dev/ttyUSB1
; lib_deps = knolleary/PubSubClient@^2.8
